<?php

require("fpdf/fpdf.php");
$pdf = new FPDF();
$day = date("d");
$month=date("M");
$year=date("Y");
$name = ($_POST['name']);
$address= ($_POST['address']);
$bus_name=($_POST['bus_name']);
$paragraph1 = "                    with the business address at  ".$address."";
$paragraph2 = "                    This further certifies that ".$bus_name." is not erected on public sidewalk avenue park, or plaza, or any governmanent property neither nuisance to public safety and order. That there was no abuse or privilege to do business or pursue an activity to the injury of the public moral and peace.";
$paragraph3 = "                    This certification is being issued upon the request ".$name." for the application of business permit, subject to all regulations prescribed by the City Government. This certification is valid only for one year from the date of issuance";
$paragraph4 = "                    Issued this ".$day." of ";
$paragraph44="".$month.", year ";
$paragraph444="".$year." at Barangay 599 Zone 59, District VI, City of Manila.";
$pdf->SetAuthor('Mark Porcalla');
$pdf->SetTitle ('busClearance');
$pdf->SetFont('Helvetica','B',20);
$pdf->SetTextColor(50,60,100);
$pdf->AddPage('P');
$pdf->SetXY(50,20);
$pdf->SetDrawColor(50,60,100);
$pdf->Cell(100,10,'BUSINESS CLEARANCE',1,0,'C',0);
$pdf->SetXY(10,50);
$pdf->SetFontSize(10);
$pdf->Cell(180,0,'this is to certify that',0,0,'C',0);
$pdf->SetFontSize(20);
$pdf->Cell(-180,15,$name,0,0,'C',0);
$pdf->SetXY(10,50);
$pdf->SetFontSize(10);
$pdf->Ln(30);
$pdf->Cell(180,0,'is the owner of',0,0,'C',0);
$pdf->SetFontSize(20);
$pdf->Cell(-180,15,$bus_name,0,0,'C',0);
$pdf->SetXY(10,50);
$pdf->SetFontSize(10);
$pdf->Ln(45);
$pdf->Write(10,$paragraph1);
$pdf->Ln(8);
$pdf->Write(10,$paragraph2);
$pdf->Ln(8);
$pdf->Write(10,$paragraph3);
$pdf->Ln(8);
$pdf->Write(10,$paragraph4);
$pdf->Write(10,$paragraph44);
$pdf->Write(10,$paragraph444);
$pdf->Ln(15);
$pdf->Write(10,'                                                                                                                                                       certified by:');
$pdf->Ln(20);
$pdf->Write(10,'                                                                                                                                             SALVADOR C. ONANAD');
$pdf->Ln(10);
$pdf->Write(5,'                                                                                                                                                  Barangay Captain');
$pdf->Ln(10);
$pdf->Write(10,'Kagawad on Duty');
$pdf->Ln(20);
$pdf->Write(10,'Prepared by:');
$pdf->Ln(20);
$pdf->Write(10,'MARIVIC M. VILLAREAL');
$pdf->Ln(10);
$pdf->Write(5,'Barangay Secretary');
$pdf->Output('Business-Clearance.pdf','I');
?>