<?php

require("fpdf/fpdf.php");
$pdf = new FPDF();
$pdf->SetAuthor('Mark Porcalla');
$pdf->SetTitle ('CertificateOfIndigency');
$pdf->SetFont('Helvetica','B',20);
$pdf->SetTextColor(50,60,100);
$pdf->AddPage('P');
$pdf->SetFontSize(10);
$pdf->Cell(280,10,'Barangay Case#',0,0,'C',0);
$pdf->Ln(20);
$pdf->Cell(50,10,'Complainant',0,0,'C',0);
$pdf->Cell(240,10,'Respondent',0,0,'C',0);
$pdf->SetXY(50,20);
$pdf->SetDrawColor(50,60,100);
$pdf->SetFontSize(20);
$pdf->Ln(15);
$pdf->Write(10,'--------------------------------------------------------------------------------');
$pdf->Ln(10);
$pdf->Cell(200,10,'CERTIFICATE OF FILE ACTION',0,0,'C',0);
$pdf->SetXY(10,50);
$pdf->SetFontSize(10);
$pdf->Ln(5);
$pdf->Write(5,'This is to certify that:');
$pdf->Ln(10);
$pdf->Write(10,'                               1. There has been a personal confrontation between the parties before the Punong Barangay,');
$pdf->Ln(10);
$pdf->Write(10,'                               but mediation failed;');
$pdf->Ln(10);
$pdf->Write(10,'                               2. The Punong Barangay set the meeting of the parties for the constitution of the Pangkat ng');
$pdf->Ln(10);
$pdf->Write(10,'                               Tagapagkasundo;');
$pdf->Ln(10);
$pdf->Write(10,'                               3. The Pangkat ng Tagapagkasundo was constituted and again mediation failed');
$pdf->Ln(20);
$pdf->Write(10,'Therefore, the corresponding complaint for the dispute may now be filed in court.');
$pdf->Ln(15);
$pdf->Write(10,'This             day of                               ');
$pdf->Ln(20);
$pdf->Write(10,'                                                                                                                                                       certified by:');
$pdf->Ln(20);
$pdf->Write(10,'                                                                                                                                             SALVADOR C. ONANAD');
$pdf->Ln(10);
$pdf->Write(5,'                                                                                                                                                  Punong Barangay');
$pdf->Ln(30);
$pdf->Write(10,'Prepared by:');
$pdf->Ln(20);
$pdf->Write(10,'MARIVIC M. VILLAREAL');
$pdf->Ln(10);
$pdf->Write(5,'Barangay Secretary');
$pdf->Output('Certificate-Of-Indigency.pdf','I');
?>